### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by enzodanjour** [ubuntu-flutter-community/settings#318]
I`m trying run the project and have this error, what i can do to resolve that ?

flutter run -v:
```
[   +1 ms] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_atomic_ref_count_init'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_atomic_ref_count_dec'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_atomic_ref_count_inc'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `log2@GLIBC_2.29'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to
`gtk_event_controller_key_new'
[        ] /usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `pow@GLIBC_2.29'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +1 ms] ninja: build stopped: subcommand failed.
[   +9 ms] Building Linux application... (completed in 4.0s)
[+7256 ms] Exception: Build process failed
[   +1 ms] "flutter run" took 11,868ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +108 ms] ensureAnalyticsSent: 106ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by Feichtmeier** [comment]
Hi! What version of Ubuntu do you run?

It might be related to the libhandy version prior to 21.10

I need to get https://pub.dev/packages/handy_window in so we don't need us to to install libhandy-dev  libs

**Comment by Feichtmeier** [comment]
@enzodanjour could you check the branch "handy_window" / test the linked PR to see if this error goes away now?

**Comment by Feichtmeier** [comment]
I personally never saw this issue myself and due to no reaction, I close it now
